#!/usr/bin/python2.6
# Copyright 2006 John Duda 

# This file is part of Infoshopkeeper.

# Infoshopkeeper is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or any later version.

# Infoshopkeeper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Infoshopkeeper; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301
# USA

#Boa:App:BoaApp
try:
    import wxversion
    wxversion.select("2.6")
except Exception, e:
    import sys
    print >> sys.stderr, "%s: wxPython 2.6 not installed." %e
    sys.exit(1)

from infoshopkeeper_config import configuration

from wxPython.wx import *

import wxFrame1

modules ={'item': [0, '', 'item.py'],
 'numericDisplay': [0, '', 'numericDisplay.py'],
 'orderDisplay': [0, '', 'orderDisplay.py'],
 'wxFrame1': [1, 'Main frame of Application', 'wxFrame1.py']}

class BoaApp(wxApp):

    def OnInit(self):
        # Terrorize yuppies users
	#self.bitmap = wxBitmap("logo.png", wxBITMAP_TYPE_PNG)
	self.bitmap=False
        if (self.bitmap):
            splash = wxSplashScreen(self.bitmap,
                 wxSPLASH_CENTRE_ON_SCREEN|wxSPLASH_TIMEOUT,
                 6000, NULL, -1, wxDefaultPosition, wxDefaultSize,
                 wxFRAME_NO_TASKBAR|wxSTAY_ON_TOP)
        wxInitAllImageHandlers()
        self.main = wxFrame1.create(None)
        # needed when running from Boa under Windows 9X
        self.SetTopWindow(self.main)
        self.main.Show();
        return True

def main():
   application = BoaApp(0)
   application.MainLoop()

if __name__ == '__main__':
    main()
