#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Skeleton import Skeleton

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.0.1'
__CHEETAH_versionTuple__ = (2, 0, 1, 'final', 0)
__CHEETAH_genTime__ = 1309384747.6400361
__CHEETAH_genTimestamp__ = 'Wed Jun 29 17:59:07 2011'
__CHEETAH_src__ = 'TitleEditTemplate.html'
__CHEETAH_srcLastModified__ = 'Sun Apr 18 18:17:10 2010'
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class TitleEditTemplate(Skeleton):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Skeleton.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def pagetitle(self, **KWS):



        ## CHEETAH: generated from #def pagetitle at line 4, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''Editing ''')
        _v = VFFSL(SL,"title.booktitle",True) # '${title.booktitle}' on line 5, col 9
        if _v is not None: write(_filter(_v, rawExpr='${title.booktitle}')) # from line 5, col 9.
        write('''
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def body(self, **KWS):



        ## CHEETAH: generated from #def body at line 8, col 1.
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<h1>Edit a Title</h1>

<form method="get" action="/titleedit">
''')
        _v = VFFSL(SL,"title.object_to_form",True) # '$title.object_to_form' on line 12, col 1
        if _v is not None: write(_filter(_v, rawExpr='$title.object_to_form')) # from line 12, col 1.
        write('''
</form>
<h2>Author(s):</h2>
''')
        for a in VFFSL(SL,"title.author",True): # generated from line 15, col 1
            write('''<div><span>''')
            _v = VFFSL(SL,"a.author_name",True) # '$a.author_name' on line 16, col 12
            if _v is not None: write(_filter(_v, rawExpr='$a.author_name')) # from line 16, col 12.
            write('''</span><a class="listinglink" href="/authoredit?id=''')
            _v = VFFSL(SL,"a.id",True) # '$a.id' on line 16, col 77
            if _v is not None: write(_filter(_v, rawExpr='$a.id')) # from line 16, col 77.
            write('''">edit</a></div>
''')
        write('''

<h2>Copies</h2>
<form action="/addtocart">
''')
        for b in VFFSL(SL,"title.books",True): # generated from line 22, col 1
            write('''<div class="listinggroup">
<table>
<tr>
<td>
<a class="listinglink" href="/bookedit?id=''')
            _v = VFFSL(SL,"b.id",True) # '$b.id' on line 27, col 43
            if _v is not None: write(_filter(_v, rawExpr='$b.id')) # from line 27, col 43.
            write('''">edit</a>
</td>
<td>
<b>copy from ''')
            _v = VFFSL(SL,"b.distributor",True) # '$b.distributor' on line 30, col 14
            if _v is not None: write(_filter(_v, rawExpr='$b.distributor')) # from line 30, col 14.
            write(''' (''')
            _v = VFFSL(SL,"b.notes",True) # '$b.notes' on line 30, col 30
            if _v is not None: write(_filter(_v, rawExpr='$b.notes')) # from line 30, col 30.
            write(''') owned by ''')
            _v = VFFSL(SL,"b.owner",True) # '$b.owner' on line 30, col 49
            if _v is not None: write(_filter(_v, rawExpr='$b.owner')) # from line 30, col 49.
            write(''' <br />inventoried on ''')
            _v = VFFSL(SL,"b.inventoried_when",True) # '$b.inventoried_when' on line 30, col 79
            if _v is not None: write(_filter(_v, rawExpr='$b.inventoried_when')) # from line 30, col 79.
            write(''' at $''')
            _v = VFFSL(SL,"b.listprice",True) # '$b.listprice' on line 30, col 104
            if _v is not None: write(_filter(_v, rawExpr='$b.listprice')) # from line 30, col 104.
            write('''<br /> with status ''')
            _v = VFFSL(SL,"b.status",True) # '$b.status' on line 30, col 135
            if _v is not None: write(_filter(_v, rawExpr='$b.status')) # from line 30, col 135.
            write('''
''')
            if VFFSL(SL,"b.status",True)=="SOLD": # generated from line 31, col 1
                write('''(''')
                _v = VFFSL(SL,"b.sold_when",True) # '$b.sold_when' on line 32, col 2
                if _v is not None: write(_filter(_v, rawExpr='$b.sold_when')) # from line 32, col 2.
                write(''')
''')
            write('''<br /></b>
</td>
<td>
add this copy to cart: <input type="checkbox" name="copy_id" value="''')
            _v = VFFSL(SL,"b.id",True) # '$b.id' on line 37, col 69
            if _v is not None: write(_filter(_v, rawExpr='$b.id')) # from line 37, col 69.
            write('''" />
[add <input style="width:80px;"type="text" length="3" name="select_x_like_''')
            _v = VFFSL(SL,"b.id",True) # '$b.id' on line 38, col 75
            if _v is not None: write(_filter(_v, rawExpr='$b.id')) # from line 38, col 75.
            write('''" value="" /> copies like this to cart]
</td>
</tr>
</table>
</div>
''')
        write('''<input class="submit" type="submit" name="addtocart" value="Collect selected copies" /> <br /> <!--<br />
<input class="submit" type="submit" name="delete" onclick="return confirm(\'Are you sure?\');" value="Delete selected copies" />-->
</form>

<h2>Categories:</h2>
''')
        for c in VFFSL(SL,"title.categorys",True): # generated from line 49, col 1
            write('''<div class="listing"><span class="listing">''')
            _v = VFFSL(SL,"c.categoryName",True) # '$c.categoryName' on line 50, col 44
            if _v is not None: write(_filter(_v, rawExpr='$c.categoryName')) # from line 50, col 44.
            write('''</span><a class="listinglink" href="/categoryedit?id=''')
            _v = VFFSL(SL,"c.id",True) # '$c.id' on line 50, col 112
            if _v is not None: write(_filter(_v, rawExpr='$c.id')) # from line 50, col 112.
            write('''">edit</a></div>
''')
        write('''


''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        

    def writeBody(self, **KWS):



        ## CHEETAH: main method generated for this template
        trans = KWS.get("trans")
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''

''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_TitleEditTemplate= 'writeBody'

## END CLASS DEFINITION

if not hasattr(TitleEditTemplate, '_initCheetahAttributes'):
    templateAPIClass = getattr(TitleEditTemplate, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(TitleEditTemplate)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=TitleEditTemplate()).run()


